language: bash
dist: xenial
services:
  - docker
before_script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - echo "test done"
after_success:
  - docker build -t xiaoshenge/alpine .
  - docker push xiaoshenge/alpine